Implement LTE cell metrics
netlab-sapienza/docker-telegraf-influx-grafana-stack pull request #5
Opened 2023-10-09 19:57 UTC by CogSP

implemented and organized LTE cell metrics

2023-10-09 20:37 UTC, Thecave3 requested changes
Indentation should be reviewed.

why are we using these names (`-number`) for the dashboard in grafana? Can we normalize them?

2023-10-09 20:37 UTC, Thecave3 commented on statsd_ns3/sim_watcher.py
>                  values[i] = values[i]*pow(10, -1)
Please add a comment on the dashboard plot of this metric where it is explained the conversion done during the preprocessing

2023-10-09 20:37 UTC, Thecave3 commented on statsd_ns3/sim_watcher.py
> +            if field == 'L3 serving Id(m_cellId)' or field == 'L3 serving SINR' or field == 'L3 serving SINR 3gpp' or field == 'L3 neigh Id 1 (cellId)' or field == 'L3 neigh SINR 1' or field == 'L3 n
```suggestion
# Create a static array as member of the class and put all of these string values inside
# after doing this, check if the value is in the array
            if field in named_array:
```

2023-10-09 20:37 UTC, Thecave3 commented on statsd_ns3/sim_watcher.py
> +                i+=1
try to be consistent in the indentation.

2023-10-11 13:44 UTC, CogSP commented on statsd_ns3/sim_watcher.py
>                  values[i] = values[i]*pow(10, -1)
I have added this description on the panel

![image](https://github.com/netlab-sapienza/docker-telegraf-influx-grafana-stack/assets/100959950/690e2e4e-0c8d-4cba-8972-cd7783adab90)

2023-10-11 13:53 UTC, CogSP commented on statsd_ns3/sim_watcher.py
> +                i+=1
Ok, I have reviewed the indentation.

2023-10-11 15:12 UTC, CogSP commented on statsd_ns3/sim_watcher.py
> +            if field == 'L3 serving Id(m_cellId)' or field == 'L3 serving SINR' or field == 'L3 serving SINR 3gpp' or field == 'L3 neigh Id 1 (cellId)' or field == 'L3 neigh SINR 1' or field == 'L3 n
Ok, I have done it

![image](https://github.com/netlab-sapienza/docker-telegraf-influx-grafana-stack/assets/100959950/12c3f948-6180-4e2b-a8c5-04362e6e15cc)

![image](https://github.com/netlab-sapienza/docker-telegraf-influx-grafana-stack/assets/100959950/c4ed008b-bea1-42a7-9e52-32bf178908e6)

2023-10-11 15:41 UTC, CogSP commented
> Indentation should be reviewed.
> 
> why are we using these names (`-number`) for the dashboard in grafana? Can we normalize them?

Do you mean these?

![image](https://github.com/netlab-sapienza/docker-telegraf-influx-grafana-stack/assets/100959950/9d3d8c66-c6d5-4d8e-a64f-11ed0c3315ec)

![image](https://github.com/netlab-sapienza/docker-telegraf-influx-grafana-stack/assets/100959950/d648c7bc-3a4e-44b2-b9a8-cb346df80f74)

![image](https://github.com/netlab-sapienza/docker-telegraf-influx-grafana-stack/assets/100959950/d50b2923-a736-4ffa-bc16-7d2af2e4d414)


These are not shown in the Grafana front-end, but only in the JSON file name. Anyway, using [unixtimestamp.com](https://www.unixtimestamp.com/) it seems to me that they are not representing tunix timestamps (in fact they have more than 10 digits). Should I just remove `-number` from the files name?

2023-10-11 15:54 UTC, Thecave3 commented
> These are not shown in the Grafana front-end, but only in the JSON file name. Anyway, using [unixtimestamp.com](https://www.unixtimestamp.com/) it seems to me that they are not representing tunix timestamps (in fact they have more than 10 digits). Should I just remove `-number` from the files name?

yes

2023-10-11 15:56 UTC, Thecave3 commented
When you are ready for a new review, ask me to check.

2023-10-12 12:43 UTC, CogSP commented
@Thecave3 I am ready for a new review

2023-10-12 20:23 UTC, Thecave3 requested changes
let's call the jsons:
- cu_cp.json
- du.json
- cu_up.json
- aggregated.json

2023-10-12 20:23 UTC, Thecave3 commented on statsd_ns3/sim_watcher.py
> +    L3_SINR_id = ['L3 serving Id(m_cellId)', 'L3 serving SINR', 'L3 serving SINR 3gpp','L3 neigh Id 1 (cellId)', 'L3 neigh SINR 1', 'L3 neigh SINR 3gpp 1 (convertedSinr)', 'L3 neigh Id 2 (cellId)', '
```suggestion
    l3sinr_fieldnames = ['L3 serving Id(m_cellId)', 'L3 serving SINR', 'L3 serving SINR 3gpp','L3 neigh Id 1 (cellId)', 'L3 neigh SINR 1', 'L3 neigh SINR 3gpp 1 (convertedSinr)', 'L3 neigh Id 2 (cellId)', 'L3 neigh SINR 2', 'L3 neigh SINR 3gpp 2 (convertedSinr)', 'L3 neigh Id 3 (cellId)', 'L3 neigh SINR 3', 'L3 neigh SINR 3gpp 3 (convertedSinr)', 'L3 neigh Id 4 (cellId)', 'L3 neigh SINR 4', 'L3 neigh SINR 3gpp 4 (convertedSinr)', 'L3 neigh Id 5 (cellId)', 'L3 neigh SINR 5', 'L3 neigh SINR 3gpp 5 (convertedSinr)', 'L3 neigh Id 6 (cellId)', 'L3 neigh SINR 6', 'L3 neigh SINR 3gpp 6 (convertedSinr)', 'L3 neigh Id 7 (cellId)', 'L3 neigh SINR 7', 'L3 neigh SINR 3gpp 7 (convertedSinr)', 'L3 neigh Id 8 (cellId)', 'L3 neigh SINR 8', 'L3 neigh SINR 3gpp 8 (convertedSinr)']
```

2023-10-12 20:23 UTC, Thecave3 commented on statsd_ns3/sim_watcher.py
> +            if field == 'file_id_number' and (file_type == 1 or file_type == 4):
I would like this to be independent from the scenario, can we try to generalize this logic?

2023-10-12 20:23 UTC, Thecave3 commented on statsd_ns3/sim_watcher.py
> +
Why this space

2023-10-21 17:24 UTC, CogSP commented
@Thecave3 I have modified all the things above, except for this:

> I would like this to be independent from the scenario, can we try to generalize this logic?
Can you explain me exactly what do you mean with "making the logic independent from the scenario"?

  if field == 'file_id_number' and (file_type == 1 or file_type == 4):
                stat = 'L3servingID_' + ue + '_cp'
                stat = stat.replace(' ', '')
                pipe.gauge(stat = stat, value = int(values[i]), tags = {'timestamp':timestamp})
                i += 1
                continue

2023-10-21 18:58 UTC, Thecave3 commented
> @Thecave3 I have modified all the things above, except for this:
> 
> > I would like this to be independent from the scenario, can we try to generalize this logic?
> 
> Can you explain me exactly what do you mean with "making the logic independent from the scenario"?
> 
> if field == 'file_id_number' and (file_type == 1 or file_type == 4): stat = 'L3servingID_' + ue + '_cp' stat = stat.replace(' ', '') pipe.gauge(stat = stat, value = int(values[i]), tags = {'timestamp':timestamp}) i += 1 continue

This bounds this metric to scenario 0, i'd like it to work with different scenarios. The data is the same, but there are more base stations. Can we generalize these references? Check for instance scenario 1

2026-05-07 03:23 UTC, closed without merging